server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://jiaying.info:3305/lids?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Hjy20011222.

jwt:
  tokenHeader: Authorization
  secret: securesecretsecuresecretsecuresecretsecuresecretsecuresecretsecuresecretsecuresecretsecuresecretsecuresecretsecuresecretsecuresecretsecuresecret
  tokenHead: 'Bearer '

  # MyBatis mapper.xml路径配置
  mybatis:
    mapper-locations:
      - classpath:info/jiaying/back_end/dao/*.xml
      - classpath*:info/jiaying/back_end/mapper/*.xml